version: '3'
services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: 'nest-todo-server'
    expose:
      - 3000
    ports:
      - '3000:3000'
    restart: always
    depends_on:
      - mysql
      - redis
    links:
      - 'mysql:mysql'
      - 'redis:redis'
    networks:
      - default
      - inner_network
  mysql:
    image: mysql
    container_name: 'nest-todo-mysql'

    restart: always
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: 'mytodo'
    volumes:
      - ./init:/docker-entrypoint-initdb.d/
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_0900_ai_ci
      --explicit_defaults_for_timestamp=true
#      --lower_case_table_names=1
    external_links:
      - inner_network
    networks:
      - default
      - inner_network
  redis:
    image: redis
    container_name: 'nest-todo-redis'
    external_links:
      - inner_network
    networks:
      - default
      - inner_network
    restart: always
networks:
  inner_network:
    external: true
